[package]
name = "kitten"
version = "0.1.0"
authors = ["Andy Davis <github@andy-davis.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
